name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy compose
      uses: sulthonzh/docker-remote-deployment-action@v1
      with:
        remote_docker_host: ubuntu@207.127.93.93
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        copy_stack_file: true
        deploy_path: /home/ubuntu/containers/sicc
        stack_file_name: compose.yaml
        keep_files: 5
