services:
  sicc:
    image: liamnou/sicc:v1.22
    container_name: sicc
    ports:
      - 3030:3000
    restart: unless-stopped
    networks:
      - caddy-network

networks:
  caddy-network:
    external: true
