name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main
    paths:
      - 'events.yaml'
      - 'chaibuilder-nextjs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyyaml

    - name: Run Python conversion script
      run: python convert_yaml_to_chai.py
      env:
        MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      continue-on-error: false

    - name: Extract and Increment Docker version
      id: version
      run: |
        echo "$(python bump_version.py)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.7.1

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Cache Docker layers
      uses: actions/cache/restore@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx
        restore-keys: |
          ${{ runner.os }}-buildx

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        build-args: BUILDKIT_INLINE_CACHE=1
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        context: chaibuilder-nextjs
        file: chaibuilder-nextjs/Dockerfile.multistage
        push: true
        tags: liamnou/sicc:${{ env.NEW_VERSION }}
        platforms: linux/arm64

    - name: Save Docker layers
      id: cache-primes-save
      uses: actions/cache/save@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx

    - uses: stefanzweifel/git-auto-commit-action@v5
