name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'compose.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy compose
      uses: sulthonzh/docker-remote-deployment-action@v0.1.2-beta
      with:
        remote_docker_host: lestar@34.23.203.35
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        remote_docker_port: ${{ secrets.HOME_SSH_PORT }}
        copy_stack_file: true
        deploy_path: /home/lestar/sicc
        stack_file_name: compose.yaml
        keep_files: 5
        args: up -d --remove-orphans
        docker_registry_username: ${{ secrets.DOCKER_USERNAME }}
        docker_registry_password: ${{ secrets.DOCKER_PASSWORD }}
